import requests
import time
import json
import os
from threading import Thread

time_url = "https://app.bilibili.com/x/v2/splash/show"
null = ""
true = True
false = False
flag = True
counter = 0
pridect_time = 10 #ms
sale_time_str = "2022-09-26 11:00:00" #装扮开售标准时间
sale_time = int(time.mktime(time.strptime(sale_time_str, "%Y-%m-%d %H:%M:%S"))) * 1000
sale_time = int(time.time()+5)*1000
print(sale_time)

def timerThread():
    global flag, counter
    session = requests.Session()
    while flag:
        # t = time.time()
        res = session.get(url=time_url)
        # print(time.time() - t)
        client_time = int(json.loads(res.text)["data"]["splash_request_id"][0:13])
        counter += 1
        if client_time + pridect_time >= sale_time:
            flag = False
            break

def createThread():
    t1 = Thread(target=timerThread)
    t2 = Thread(target=timerThread)
    t3 = Thread(target=timerThread)
    t4 = Thread(target=timerThread)
    t5 = Thread(target=timerThread)
    t6 = Thread(target=timerThread)
    t7 = Thread(target=timerThread)
    t8 = Thread(target=timerThread)
    t9 = Thread(target=timerThread)
    t10 = Thread(target=timerThread)
    t11 = Thread(target=timerThread)
    t12 = Thread(target=timerThread)
    t13 = Thread(target=timerThread)
    t14 = Thread(target=timerThread)
    t15 = Thread(target=timerThread)
    t16 = Thread(target=timerThread)
    t17 = Thread(target=timerThread)
    t18 = Thread(target=timerThread)
    t19 = Thread(target=timerThread)
    t20 = Thread(target=timerThread)
    t21 = Thread(target=timerThread)
    t22 = Thread(target=timerThread)
    t23 = Thread(target=timerThread)
    t24 = Thread(target=timerThread)
    t25 = Thread(target=timerThread)
    t26 = Thread(target=timerThread)
    t27 = Thread(target=timerThread)
    t28 = Thread(target=timerThread)
    t29 = Thread(target=timerThread)
    t30 = Thread(target=timerThread)
    t31 = Thread(target=timerThread)
    t32 = Thread(target=timerThread)
    t33 = Thread(target=timerThread)
    t34 = Thread(target=timerThread)
    t35 = Thread(target=timerThread)
    t36 = Thread(target=timerThread)
    t37 = Thread(target=timerThread)
    t38 = Thread(target=timerThread)
    t39 = Thread(target=timerThread)
    t40 = Thread(target=timerThread)
    t41 = Thread(target=timerThread)
    t42 = Thread(target=timerThread)
    t43 = Thread(target=timerThread)
    t44 = Thread(target=timerThread)
    t45 = Thread(target=timerThread)
    t46 = Thread(target=timerThread)
    t47 = Thread(target=timerThread)
    t48 = Thread(target=timerThread)
    t49 = Thread(target=timerThread)
    t50 = Thread(target=timerThread)
    t51 = Thread(target=timerThread)
    t52 = Thread(target=timerThread)
    t53 = Thread(target=timerThread)
    t54 = Thread(target=timerThread)
    t55 = Thread(target=timerThread)
    t56 = Thread(target=timerThread)
    t57 = Thread(target=timerThread)
    t58 = Thread(target=timerThread)
    t59 = Thread(target=timerThread)
    t60 = Thread(target=timerThread)
    t61 = Thread(target=timerThread)
    t62 = Thread(target=timerThread)
    t63 = Thread(target=timerThread)
    t64 = Thread(target=timerThread)
    t65 = Thread(target=timerThread)
    t66 = Thread(target=timerThread)
    t67 = Thread(target=timerThread)
    t68 = Thread(target=timerThread)
    t69 = Thread(target=timerThread)
    t70 = Thread(target=timerThread)
    t71 = Thread(target=timerThread)
    t72 = Thread(target=timerThread)
    t73 = Thread(target=timerThread)
    t74 = Thread(target=timerThread)
    t75 = Thread(target=timerThread)
    t76 = Thread(target=timerThread)
    t77 = Thread(target=timerThread)
    t78 = Thread(target=timerThread)
    t79 = Thread(target=timerThread)
    t80 = Thread(target=timerThread)
    t81 = Thread(target=timerThread)
    t82 = Thread(target=timerThread)
    t83 = Thread(target=timerThread)
    t84 = Thread(target=timerThread)
    t85 = Thread(target=timerThread)
    t86 = Thread(target=timerThread)
    t87 = Thread(target=timerThread)
    t88 = Thread(target=timerThread)
    t89 = Thread(target=timerThread)
    t90 = Thread(target=timerThread)
    t91 = Thread(target=timerThread)
    t92 = Thread(target=timerThread)
    t93 = Thread(target=timerThread)
    t94 = Thread(target=timerThread)
    t95 = Thread(target=timerThread)
    t96 = Thread(target=timerThread)
    t97 = Thread(target=timerThread)
    t98 = Thread(target=timerThread)
    t99 = Thread(target=timerThread)
    t100 = Thread(target=timerThread)
    t101 = Thread(target=timerThread)
    t102 = Thread(target=timerThread)
    t103 = Thread(target=timerThread)
    t104 = Thread(target=timerThread)
    t105 = Thread(target=timerThread)
    t106 = Thread(target=timerThread)
    t107 = Thread(target=timerThread)
    t108 = Thread(target=timerThread)
    t109 = Thread(target=timerThread)
    t110 = Thread(target=timerThread)
    t111 = Thread(target=timerThread)
    t112 = Thread(target=timerThread)
    t113 = Thread(target=timerThread)
    t114 = Thread(target=timerThread)
    t115 = Thread(target=timerThread)
    t116 = Thread(target=timerThread)
    t117 = Thread(target=timerThread)
    t118 = Thread(target=timerThread)
    t119 = Thread(target=timerThread)
    t120 = Thread(target=timerThread)
    t121 = Thread(target=timerThread)
    t122 = Thread(target=timerThread)
    t123 = Thread(target=timerThread)
    t124 = Thread(target=timerThread)
    t125 = Thread(target=timerThread)
    t126 = Thread(target=timerThread)
    t127 = Thread(target=timerThread)
    t128 = Thread(target=timerThread)
    t1.start()
    t2.start()
    t3.start()
    t4.start()
    t5.start()
    t6.start()
    t7.start()
    t8.start()
    t9.start()
    t10.start()
    t11.start()
    t12.start()
    t13.start()
    t14.start()
    t15.start()
    t16.start()
    t17.start()
    t18.start()
    t19.start()
    t20.start()
    t21.start()
    t22.start()
    t23.start()
    t24.start()
    t25.start()
    t26.start()
    t27.start()
    t28.start()
    t29.start()
    t30.start()
    t31.start()
    t32.start()
    t33.start()
    t34.start()
    t35.start()
    t36.start()
    t37.start()
    t38.start()
    t39.start()
    t40.start()
    t41.start()
    t42.start()
    t43.start()
    t44.start()
    t45.start()
    t46.start()
    t47.start()
    t48.start()
    t49.start()
    t50.start()
    t51.start()
    t52.start()
    t53.start()
    t54.start()
    t55.start()
    t56.start()
    t57.start()
    t58.start()
    t59.start()
    t60.start()
    t61.start()
    t62.start()
    t63.start()
    t64.start()
    t65.start()
    t66.start()
    t67.start()
    t68.start()
    t69.start()
    t70.start()
    t71.start()
    t72.start()
    t73.start()
    t74.start()
    t75.start()
    t76.start()
    t77.start()
    t78.start()
    t79.start()
    t80.start()
    t81.start()
    t82.start()
    t83.start()
    t84.start()
    t85.start()
    t86.start()
    t87.start()
    t88.start()
    t89.start()
    t90.start()
    t91.start()
    t92.start()
    t93.start()
    t94.start()
    t95.start()
    t96.start()
    t97.start()
    t98.start()
    t99.start()
    t100.start()
    t101.start()
    t102.start()
    t103.start()
    t104.start()
    t105.start()
    t106.start()
    t107.start()
    t108.start()
    t109.start()
    t110.start()
    t111.start()
    t112.start()
    t113.start()
    t114.start()
    t115.start()
    t116.start()
    t117.start()
    t118.start()
    t119.start()
    t120.start()
    t121.start()
    t122.start()
    t123.start()
    t124.start()
    t125.start()
    t126.start()
    t127.start()
    t128.start()

def main():
    global flag, counter
    session = requests.Session()
    session.get(url=time_url)
    t = time.time()
    # print("test0")
    createThread()
    
    while True:
        if not flag:
            # print("test1")
            e = time.time()
            print((e-t)*1000/counter)
            print(json.loads(session.get(url=time_url).text)["data"]["splash_request_id"][0:13])
            # print(time.time())
            break
    os.system("pause")

if __name__ == "__main__":
    main()
